CC =  cc
CFLAGS = -Wall -Wextra -Werror

OBJS  = $(SRCS:.c=.o)

SRCS = ft_atoi.c ft_itoa.c ft_bzero.c ft_calloc.c\
		ft_isalnum.c ft_isalpha.c ft_isascii.c ft_isdigit.c ft_isprint.c \
		ft_memchr.c ft_memcmp.c ft_memcpy.c ft_memmove.c ft_memset.c \
		ft_putchar_fd.c ft_putendl_fd.c ft_putnbr_fd.c ft_putstr_fd.c \
		ft_split.c ft_strchr.c ft_strrchr.c ft_strdup.c ft_striteri.c \
		ft_strjoin.c ft_strlcat.c ft_strlcpy.c ft_strlen.c ft_strmapi.c \
		ft_strncmp.c ft_strnstr.c ft_strtrim.c ft_substr.c ft_tolower.c \
		ft_toupper.c ft_isspace.c ft_issign.c ft_atol.c ft_error.c ft_free.c \
		ft_strslen.c ft_strcmp.c get_next_line/get_next_line.c get_next_line/get_next_line_utils.c

NAME = libft.a
ARFLAGS = src

all : ${NAME}

${NAME} : ${OBJS}
	ar ${ARFLAGS} $@ $^

.c.o :
	${CC} ${CFLAGS} -c $< -o $@

clean :
	rm -f ${OBJS}

fclean : clean 
	rm -f ${NAME}

re : fclean all

.PHONY : all bonus clean fclean re
